title: Vindicta Player Guide
description: "The player guide for the Arma 3 modification Vindicta: Guerrilla Warfare."
remote_theme: pmarsceill/just-the-docs


# Theme settings:
color_scheme: "dark"
logo: 'https://user-images.githubusercontent.com/1453936/73617285-e1372800-4614-11ea-81a1-5abe83abfe19.png'

# Aux links for the upper right navigation
aux_links:
  "Steam Workshop Page":
    - "//steamcommunity.com/sharedfiles/filedetails/?id=1964186045"
  "Discord":
    - "//discord.gg/CPkgHuN"
  "BI Forum Page":
    - "//forums.bohemia.net/forums/topic/227302-mpcoop-vindicta-alpha/"
  "GitHub Page":
    - "//github.com/Sparker95/Vindicta"

# Footer content appears at the bottom of every page's main content
footer_content: ''

search_enabled: true

# Footer metadata
show_last_edit_time: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
show_gh_edit_link: true
gh_edit_repository: "https://github.com/Sparker95/Vindicta" # the github URL for your repo
gh_edit_branch: "master/docs" # switch to the branch that your docs is served from
gh_edit_view_mode: "edit" # switch to "edit" if you want the user to jump into the editor immediately
edit_link_text: "Edit this page on GitHub."
